class_name BufScript extends Resource

@export var timing: TIMING = TIMING.FULL_SECOND_TICK

enum TIMING{
	WHEN_INIT, WHEN_DESTROYED,
	HALF_SECOND_TICK, FULL_SECOND_TICK,
	STACK_UPDATE,
	ON_HIT_BEFORE, ON_HIT_AFTER,
	WHEN_HIT_BEFORE, WHEN_HIT_AFTER,
	RECEIVE_DAMAGE_BEFORE, RECEIVE_DAMAGE_AFTER
}

func Enact(buf: Buf) -> void: pass
